apiVersion: apps/v1
kind: Deployment
metadata:
  name: orangehrm
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: orangehrm
          image: orangehrm/orangehrm:5.8.1
          imagePullPolicy: IfNotPresent
