apiVersion: v1
kind: Secret
metadata:
  name: orangehrm-db-secret
  namespace: hrm
type: Opaque
stringData:
  MARIADB_DATABASE: orangehrm
  MARIADB_USER: orangehrm
  MARIADB_PASSWORD: orangehrm
  MARIADB_ROOT_PASSWORD: root
  DB_PASS: orangehrm
